### ISSUE TITLE
User Story: Auto-off  alarm

### ISSUE THREAD

**Issue by Y00e** [Inotila/Wake-App#9]
As a **user** who often waeks up before the alarm goes of, i forgets to turn alarm of, for example when i go to bathroom. ** i want a feature that autromatically turns off the alarm** when i have been active on the phone. ** so that when im not nearby the phone go silent**

**Comment by OlegMakeienko** [comment]
I think that the alarm should work in any case, maybe only for a short time, because the purpose of this button is not to "turn off the alarm", but to make it so that it does not ring for a long time
